spring:
  # R2DBC Configuration
  r2dbc:
    url: r2dbc:h2:mem:///documentdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    initialization-mode: always

server:
  port: 8085
