INSERT INTO DOCUMENT(NAME) VALUES('DOC1');
INSERT INTO DOCUMENT(NAME) VALUES('DOC2');
INSERT INTO DOCUMENT(NAME) VALUES('DOC3');
INSERT INTO DOCUMENT(NAME) VALUES('DOC4');
INSERT INTO DOCUMENT(NAME) VALUES('DOC5');